//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public int Id { get; set; }
        public int Id_usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Accion { get; set; }
        public int Id_turno { get; set; }
    }
}
