//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CATALOGO : DbContext
    {
        public CATALOGO()
            : base("name=CATALOGO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<GRUPO> GRUPOS { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIOS { get; set; }
        public virtual DbSet<ACCION> ACCIONES { get; set; }
        public virtual DbSet<MODULO> MODULOS { get; set; }
        public virtual DbSet<SUBMODULO> SUBMODULOS { get; set; }
        public virtual DbSet<PARAMETRO> PARAMETROS { get; set; }
        public virtual DbSet<PLAN> PLANES { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOS { get; set; }
        public virtual DbSet<DIA_NO_LABORABLE_MEDICO> DIAS_NO_LABORABLES_MEDICOS { get; set; }
        public virtual DbSet<HORARIO_MEDICO> HORARIOS_MEDICOS { get; set; }
        public virtual DbSet<DIAS_EMPRESA> DIAS_EMPRESAS { get; set; }
        public virtual DbSet<DIAS_NO_LABORABLES> DIAS_NO_LABORABLESS { get; set; }
        public virtual DbSet<MEDICO> MEDICOS { get; set; }
        public virtual DbSet<AFILIADO> AFILIADOS { get; set; }
        public virtual DbSet<TURNO> TURNOS { get; set; }
        public virtual DbSet<DATOS_EMPRESA> DATOS_EMPRESAS { get; set; }
        public virtual DbSet<AUDITORIA> AUDITORIAs { get; set; }
        public virtual DbSet<Auditoria_Turnos> Auditoria_Turnos { get; set; }
        public virtual DbSet<DEUDA> DEUDAS { get; set; }
        public virtual DbSet<FACTURA> FACTURAS { get; set; }
        public virtual DbSet<DETALLE_FACTURA> DETALLES_FACTURAS { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOS { get; set; }
        public virtual DbSet<TARJETA> TARJETAS { get; set; }
        public virtual DbSet<RECIBO> RECIBOS { get; set; }
        public virtual DbSet<DETALLE_RECIBO> DETALLES_RECIBOS { get; set; }
    }
}
