//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_EMPRESA
    {
        public DATOS_EMPRESA()
        {
            this.DIAS_EMPRESA = new HashSet<DIAS_EMPRESA>();
            this.DIAS_NO_LABORABLES = new HashSet<DIAS_NO_LABORABLES>();
        }
    
        public int Id_Empresa { get; set; }
        public string Nombre { get; set; }
        public string Dueño { get; set; }
        public string Localidad { get; set; }
    
        public virtual ICollection<DIAS_EMPRESA> DIAS_EMPRESA { get; set; }
        public virtual ICollection<DIAS_NO_LABORABLES> DIAS_NO_LABORABLES { get; set; }
    }
}
