//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECIBO_COMPRA
    {
        public int Id_Detalle_Recibo_Compra { get; set; }
        public int Codigo_Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual RECIBO_COMPRA RECIBO_COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
