//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECIBO
    {
        public DETALLE_RECIBO()
        {
            this.DEUDAS = new HashSet<DEUDA>();
        }
    
        public int Id_Detalle_Recibo { get; set; }
        public decimal Importe { get; set; }
    
        public virtual ICollection<DEUDA> DEUDAS { get; set; }
        public virtual RECIBO RECIBO { get; set; }
    }
}
