//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public FACTURA()
        {
            this.DETALLE_FACTURA = new HashSet<DETALLE_FACTURA>();
        }
    
        public int Id_Factura { get; set; }
        public string Tipo_Factura { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Nro_Factura { get; set; }
        public int IdEstadoFactura { get; set; }
    
        public virtual AFILIADO AFILIADO { get; set; }
        public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURA { get; set; }
    }
}
