//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public MEDICO()
        {
            this.DIA_NO_LABORABLE_MEDICO = new HashSet<DIA_NO_LABORABLE_MEDICO>();
            this.HORARIO_MEDICO = new HashSet<HORARIO_MEDICO>();
            this.TURNO = new HashSet<TURNO>();
        }
    
        public int Id_Medico { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Telefono { get; set; }
        public string Email { get; set; }
        public int Matricula { get; set; }
        public int DNI { get; set; }
        public string Especialidad { get; set; }
        public bool Estado { get; set; }
        public int Tiempo_Por_Paciente { get; set; }
    
        public virtual ICollection<DIA_NO_LABORABLE_MEDICO> DIA_NO_LABORABLE_MEDICO { get; set; }
        public virtual ICollection<HORARIO_MEDICO> HORARIO_MEDICO { get; set; }
        public virtual ICollection<TURNO> TURNO { get; set; }
    }
}
