//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO
    {
        public int ID { get; set; }
        public string DIRECTORIO_IMAGENES { get; set; }
        public bool ENVIO_MAILS { get; set; }
        public string MAIL_CUENTA { get; set; }
        public string MAIL_CLAVE { get; set; }
        public string MAIL_NOMBRE_REMITENTE { get; set; }
        public string NOMBRE_EQUIPO { get; set; }
    }
}
