//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN
    {
        public PLAN()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
            this.AFILIADO = new HashSet<AFILIADO>();
        }
    
        public int Id_Plan { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
        public virtual ICollection<AFILIADO> AFILIADO { get; set; }
    }
}
