//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        public RECIBO()
        {
            this.DETALLE_RECIBO = new HashSet<DETALLE_RECIBO>();
        }
    
        public int Id_Recibo { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Importe { get; set; }
        public int Nro_Recibo { get; set; }
    
        public virtual ICollection<DETALLE_RECIBO> DETALLE_RECIBO { get; set; }
        public virtual AFILIADO AFILIADO { get; set; }
    }
}
