//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBMODULO
    {
        public SUBMODULO()
        {
            this.FORMULARIO = new HashSet<FORMULARIO>();
        }
    
        public int CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
    }
}
