//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public int Id_Tarjeta { get; set; }
        public string Titular { get; set; }
        public long Numero { get; set; }
        public string Vencimiento { get; set; }
    
        public virtual AFILIADO AFILIADO { get; set; }
    }
}
