//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        public int Id_Turno { get; set; }
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public bool Concurrio { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
        public virtual AFILIADO AFILIADO { get; set; }
    }
}
