//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.GRUPO = new HashSet<GRUPO>();
        }
    
        public int CODIGO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string CLAVE { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public bool ACTIVO { get; set; }
        public bool RESETEAR_CLAVE { get; set; }
        public string IMAGEN { get; set; }
    
        public virtual ICollection<GRUPO> GRUPO { get; set; }
    }
}
